
GET http://localhost:3000/posts

Authorization: Bearer 
{
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJyZXQiLCJlbWFpbCI6IlNpbmNlcmVAYXByaWwuYml6IiwiaWF0IjoxNjk1NzI2OTgyLCJleHAiOjE2OTU3MjY5OTd9.FV2w2B61kzO1FVC_voffQzoCzMTkQuOxxJdTnDFoi4Q"
}

### 
POST http://localhost:3000/login
content-type: application/json

{
    "username": "Bret",
    "email": "Sincere@april.biz"
}

###

POST http://localhost:4000/token
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVC
    J9.eyJ1c2VybmFtZSI6InRvbW15IiwicGFzc3dvcmQiOiJ0b21lcjEiLCJpYXQiOjE2OTUyMDUxMzh9.PjQakt0-T63ILzO051BqgPO4j7TlkR9TC0Uz-372cJo"

}

###

DELETE http://localhost:3000/logout
content-type: application/json

{
    // refresh access key that is stored in the database goes here
    "token":
}

###

GET http://localhost:3000/employees

###
# Valid employee id in employess collection
GET http://localhost:3000/employees/edit/651529fd7e50224abf3be896

###
# Invalid employee id in employess collection
GET http://localhost:3000/employees/edit/651529fd7e50224abf3b


###
# Delete user from mongo db employees collection
DELETE http://localhost:3000/employees/edit/651ad4b7809bdcd1208d131d

###
# Update employee's information on mongo db employees collection
PUT http://localhost:3000/employees/edit/6515321a7e50224abf3be8d3
content-type: application/json

  {
    "firstName": "Billy",
    "lastName": "Story",
    "startWorkYear": 2018,
    "departmentName": "Main"
  }